export enum TasksActionTypes {
    FETCH_TASKS = "FETCH_TASKS",
    FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS",
    FETCH_ADD_TASK = "FETCH_ADD_TASK",
    ADD_TASK = "ADD_TASK",
    DEL_TASK = "DEL_TASK",
    TOGGLE_TASK = "TOGGLE_TASK"
}